# Generated by Django 5.1.1 on 2024-09-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_list_app', '0002_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name_plural': 'summaries'},
        ),
    ]
